// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Controlador Seguidor Solar

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////
int azimutValue = 0; // Variable global para almacenar el valor de azimut

void OPAON_Animation(lv_obj_t * TargetObject, int delay);
void OPAOFF_Animation(lv_obj_t * TargetObject, int delay);
void Glow_Animation(lv_obj_t * TargetObject, int delay);


// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
lv_obj_t * ui_Screen1;
lv_obj_t * ui_imgFondo;
lv_obj_t * ui_Panel_Principal;
lv_obj_t * ui_PanelMove;
lv_obj_t * ui_btnBgMove;
void ui_event_Glow_R(lv_event_t * e);
lv_obj_t * ui_Glow_R;
void ui_event_Glow_L(lv_event_t * e);
lv_obj_t * ui_Glow_L;
void ui_event_Glow_U(lv_event_t * e);
lv_obj_t * ui_Glow_U;
void ui_event_Glow_D(lv_event_t * e);
lv_obj_t * ui_Glow_D;
lv_obj_t * ui_btnBgMoveTop;
lv_obj_t * ui_btnRigth;
lv_obj_t * ui_btnUp;
lv_obj_t * ui_btnLeft;
lv_obj_t * ui_btnDown;
lv_obj_t * ui_ContainerWeather;
lv_obj_t * ui_Image17;
lv_obj_t * ui_Image19;
lv_obj_t * ui_ContainerVariables;
lv_obj_t * ui_PanelVariables;
lv_obj_t * ui_PanelRad;
lv_obj_t * ui_LabelVarRad;
lv_obj_t * ui_LabelTitle;
lv_obj_t * ui_LabelUnits;
lv_obj_t * ui_icon;
lv_obj_t * ui_Line;
lv_obj_t * ui_PanelTemp;
lv_obj_t * ui_LabelVarTemp;
lv_obj_t * ui_LabelTitle1;
lv_obj_t * ui_LabelUnits1;
lv_obj_t * ui_icon1;
lv_obj_t * ui_PanelVariables1;
lv_obj_t * ui_PanelHum;
lv_obj_t * ui_LabelVarHum;
lv_obj_t * ui_LabelTitle2;
lv_obj_t * ui_LabelUnits2;
lv_obj_t * ui_icon2;
lv_obj_t * ui_Line1;
lv_obj_t * ui_PanelTempExt;
lv_obj_t * ui_LabelVarTempExt;
lv_obj_t * ui_LabelTitle3;
lv_obj_t * ui_LabelUnits3;
lv_obj_t * ui_icon3;
lv_obj_t * ui_PanelVariables2;
lv_obj_t * ui_PanelAzimut;
lv_obj_t * ui_LabelVarAzimut;
lv_obj_t * ui_LabelTitle4;
lv_obj_t * ui_LabelUnits4;
lv_obj_t * ui_icon4;
lv_obj_t * ui_Line2;
lv_obj_t * ui_PanelCenit;
lv_obj_t * ui_LabelVarCenit;
lv_obj_t * ui_LabelTitle5;
lv_obj_t * ui_LabelUnits5;
lv_obj_t * ui_icon5;
lv_obj_t * ui_PanelMode;
lv_obj_t * ui_Container3;
lv_obj_t * ui_LabelTitle7;
void ui_event_Switch1(lv_event_t * e);
lv_obj_t * ui_Switch1;
lv_obj_t * ui_Container1;
lv_obj_t * ui_Image20;
lv_obj_t * ui_RollerModes;
lv_obj_t * ui_PanelNotification;
lv_obj_t * ui_LabelNotification;
lv_obj_t * ui_PanelNotificationIcon;
lv_obj_t * ui_icon8;
lv_obj_t * ui_icon7;
lv_obj_t * ui_icon9;
lv_obj_t * ui_PanelTimeAndDate;
lv_obj_t * ui_PanelRad3;
lv_obj_t * ui_LabelDate4;
lv_obj_t * ui_Line5;
lv_obj_t * ui_PanelTemp3;
lv_obj_t * ui_LabelDate1;
// CUSTOM VARIABLES
lv_obj_t * uic_PanelMove;
lv_obj_t * uic_btnRigth;

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
const lv_img_dsc_t * ui_imgset_456929088[1] = {&ui_img_1784134941};
const lv_img_dsc_t * ui_imgset_indicator_bg_mode[1] = {&ui_img_indicator_bg_mode2_png};

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////
void OPAON_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 100);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 250);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void OPAOFF_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 200);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 255, 0);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}
void Glow_Animation(lv_obj_t * TargetObject, int delay)
{
    ui_anim_user_data_t * PropertyAnimation_0_user_data = lv_mem_alloc(sizeof(ui_anim_user_data_t));
    PropertyAnimation_0_user_data->target = TargetObject;
    PropertyAnimation_0_user_data->val = -1;
    lv_anim_t PropertyAnimation_0;
    lv_anim_init(&PropertyAnimation_0);
    lv_anim_set_time(&PropertyAnimation_0, 1000);
    lv_anim_set_user_data(&PropertyAnimation_0, PropertyAnimation_0_user_data);
    lv_anim_set_custom_exec_cb(&PropertyAnimation_0, _ui_anim_callback_set_opacity);
    lv_anim_set_values(&PropertyAnimation_0, 0, 255);
    lv_anim_set_path_cb(&PropertyAnimation_0, lv_anim_path_linear);
    lv_anim_set_delay(&PropertyAnimation_0, delay + 0);
    lv_anim_set_deleted_cb(&PropertyAnimation_0, _ui_anim_callback_free_user_data);
    lv_anim_set_playback_time(&PropertyAnimation_0, 0);
    lv_anim_set_playback_delay(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_count(&PropertyAnimation_0, 0);
    lv_anim_set_repeat_delay(&PropertyAnimation_0, 0);
    lv_anim_set_early_apply(&PropertyAnimation_0, false);
    lv_anim_start(&PropertyAnimation_0);

}

///////////////////// FUNCTIONS ////////////////////
void ui_event_Glow_R(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_btnRigth, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        OPAON_Animation(ui_Glow_R, 0);

            // Incrementa el valor
            azimutValue += 1;
            // Convierte `azimutValue` a una cadena
            char azimutStr[2]; // Ajusta el tamaño según tus necesidades
            sprintf(azimutStr, "%d", azimutValue);

    // Actualiza el label con el valor convertido
    _ui_label_set_property(ui_LabelVarAzimut, _UI_LABEL_PROPERTY_TEXT, azimutStr);

        //_ui_label_set_property(ui_LabelVarAzimut, _UI_LABEL_PROPERTY_TEXT, "AQUI");
    }
    if(event_code == LV_EVENT_RELEASED) {
        OPAOFF_Animation(ui_Glow_R, 0);
        _ui_state_modify(ui_btnRigth, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_PRESS_LOST) {
        OPAOFF_Animation(ui_Glow_R, 0);
        _ui_state_modify(ui_btnRigth, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Glow_L(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_btnLeft, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        OPAON_Animation(ui_Glow_L, 0);
    }
    if(event_code == LV_EVENT_RELEASED) {
        OPAOFF_Animation(ui_Glow_L, 0);
        _ui_state_modify(ui_btnLeft, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_PRESS_LOST) {
        OPAOFF_Animation(ui_Glow_L, 0);
        _ui_state_modify(ui_btnLeft, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Glow_U(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_btnUp, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        OPAON_Animation(ui_Glow_U, 0);
    }
    if(event_code == LV_EVENT_RELEASED) {
        OPAOFF_Animation(ui_Glow_U, 0);
        _ui_state_modify(ui_btnUp, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_PRESS_LOST) {
        OPAOFF_Animation(ui_Glow_U, 0);
        _ui_state_modify(ui_btnUp, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Glow_D(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_PRESSED) {
        _ui_state_modify(ui_btnDown, LV_STATE_CHECKED, _UI_MODIFY_STATE_ADD);
        OPAON_Animation(ui_Glow_D, 0);
    }
    if(event_code == LV_EVENT_RELEASED) {
        OPAOFF_Animation(ui_Glow_D, 0);
        _ui_state_modify(ui_btnDown, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
    if(event_code == LV_EVENT_PRESS_LOST) {
        OPAOFF_Animation(ui_Glow_D, 0);
        _ui_state_modify(ui_btnDown, LV_STATE_CHECKED, _UI_MODIFY_STATE_REMOVE);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_roller_set_property(ui_RollerModes, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 1);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_roller_set_property(ui_RollerModes, _UI_ROLLER_PROPERTY_SELECTED_WITH_ANIM, 2);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_Screen1_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_Screen1);
}
