// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Controlador Seguidor Solar

#include "ui.h"

void ui_Screen1_screen_init(void)
{
    ui_Screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgFondo = lv_img_create(ui_Screen1);
    lv_img_set_src(ui_imgFondo, &ui_img_bg_main_png);
    lv_obj_set_width(ui_imgFondo, LV_SIZE_CONTENT);   /// 480
    lv_obj_set_height(ui_imgFondo, LV_SIZE_CONTENT);    /// 320
    lv_obj_set_align(ui_imgFondo, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgFondo, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgFondo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Panel_Principal = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_Panel_Principal, lv_pct(100));
    lv_obj_set_height(ui_Panel_Principal, lv_pct(90));
    lv_obj_set_x(ui_Panel_Principal, 1);
    lv_obj_set_y(ui_Panel_Principal, 14);
    lv_obj_set_align(ui_Panel_Principal, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel_Principal, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel_Principal, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel_Principal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel_Principal, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel_Principal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Panel_Principal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Panel_Principal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Panel_Principal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Panel_Principal, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelMove = lv_obj_create(ui_Panel_Principal);
    lv_obj_set_width(ui_PanelMove, 295);
    lv_obj_set_height(ui_PanelMove, 281);
    lv_obj_set_x(ui_PanelMove, -10);
    lv_obj_set_y(ui_PanelMove, 0);
    lv_obj_set_align(ui_PanelMove, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_PanelMove, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelMove, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMove, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelMove, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_btnBgMove = lv_img_create(ui_PanelMove);
    lv_img_set_src(ui_btnBgMove, &ui_img_btn_bg_direction_png);
    lv_obj_set_width(ui_btnBgMove, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btnBgMove, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btnBgMove, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBgMove, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_btnBgMove, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Glow_R = lv_obj_create(ui_btnBgMove);
    lv_obj_set_width(ui_Glow_R, 130);
    lv_obj_set_height(ui_Glow_R, 130);
    lv_obj_set_x(ui_Glow_R, 48);
    lv_obj_set_y(ui_Glow_R, 0);
    lv_obj_set_align(ui_Glow_R, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Glow_R, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Glow_R, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Glow_R, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Glow_R, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Glow_R, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Glow_R, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Glow_R, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Glow_R, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Glow_R, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Glow_R, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Glow_R, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Glow_R, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_Glow_R, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_Glow_R, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_Glow_R, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_Glow_R, 10, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Glow_L = lv_obj_create(ui_btnBgMove);
    lv_obj_set_width(ui_Glow_L, 130);
    lv_obj_set_height(ui_Glow_L, 130);
    lv_obj_set_x(ui_Glow_L, -48);
    lv_obj_set_y(ui_Glow_L, 0);
    lv_obj_set_align(ui_Glow_L, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Glow_L, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Glow_L, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Glow_L, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Glow_L, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Glow_L, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Glow_L, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Glow_L, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Glow_L, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Glow_L, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Glow_L, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Glow_L, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Glow_L, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_Glow_L, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_Glow_L, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_Glow_L, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_Glow_L, 10, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Glow_U = lv_obj_create(ui_btnBgMove);
    lv_obj_set_width(ui_Glow_U, 130);
    lv_obj_set_height(ui_Glow_U, 130);
    lv_obj_set_x(ui_Glow_U, 0);
    lv_obj_set_y(ui_Glow_U, -48);
    lv_obj_set_align(ui_Glow_U, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Glow_U, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Glow_U, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Glow_U, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Glow_U, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Glow_U, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Glow_U, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Glow_U, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Glow_U, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Glow_U, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Glow_U, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Glow_U, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Glow_U, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_Glow_U, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_Glow_U, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_Glow_U, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_Glow_U, 10, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_Glow_D = lv_obj_create(ui_btnBgMove);
    lv_obj_set_width(ui_Glow_D, 130);
    lv_obj_set_height(ui_Glow_D, 130);
    lv_obj_set_x(ui_Glow_D, 0);
    lv_obj_set_y(ui_Glow_D, 48);
    lv_obj_set_align(ui_Glow_D, LV_ALIGN_CENTER);
    lv_obj_set_style_radius(ui_Glow_D, 60, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Glow_D, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Glow_D, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Glow_D, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Glow_D, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Glow_D, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Glow_D, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Glow_D, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Glow_D, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Glow_D, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Glow_D, lv_color_hex(0x00D2FF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_bg_opa(ui_Glow_D, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_color(ui_Glow_D, lv_color_hex(0x60BEFF), LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_opa(ui_Glow_D, 255, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_width(ui_Glow_D, 50, LV_PART_MAIN | LV_STATE_PRESSED);
    lv_obj_set_style_shadow_spread(ui_Glow_D, 10, LV_PART_MAIN | LV_STATE_PRESSED);

    ui_btnBgMoveTop = lv_img_create(ui_btnBgMove);
    lv_img_set_src(ui_btnBgMoveTop, &ui_img_btn_bg2_direction_png);
    lv_obj_set_width(ui_btnBgMoveTop, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_btnBgMoveTop, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_btnBgMoveTop, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_btnBgMoveTop, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_btnBgMoveTop, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnRigth = lv_img_create(ui_btnBgMoveTop);
    lv_img_set_src(ui_btnRigth, &ui_img_btn_right_png);
    lv_obj_set_width(ui_btnRigth, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_btnRigth, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_btnRigth, -10);
    lv_obj_set_y(ui_btnRigth, 0);
    lv_obj_set_align(ui_btnRigth, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_btnRigth, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_btnRigth, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnUp = lv_img_create(ui_btnBgMoveTop);
    lv_img_set_src(ui_btnUp, &ui_img_btn_up_png);
    lv_obj_set_width(ui_btnUp, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_btnUp, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_btnUp, 0);
    lv_obj_set_y(ui_btnUp, 10);
    lv_obj_set_align(ui_btnUp, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_btnUp, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_btnUp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnLeft = lv_img_create(ui_btnBgMoveTop);
    lv_img_set_src(ui_btnLeft, &ui_img_btn_left_png);
    lv_obj_set_width(ui_btnLeft, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_btnLeft, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_btnLeft, 10);
    lv_obj_set_y(ui_btnLeft, 0);
    lv_obj_set_align(ui_btnLeft, LV_ALIGN_LEFT_MID);
    lv_obj_add_flag(ui_btnLeft, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_btnLeft, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_btnDown = lv_img_create(ui_btnBgMoveTop);
    lv_img_set_src(ui_btnDown, &ui_img_btn_down_png);
    lv_obj_set_width(ui_btnDown, LV_SIZE_CONTENT);   /// 30
    lv_obj_set_height(ui_btnDown, LV_SIZE_CONTENT);    /// 30
    lv_obj_set_x(ui_btnDown, 0);
    lv_obj_set_y(ui_btnDown, -10);
    lv_obj_set_align(ui_btnDown, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_btnDown, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_btnDown, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerWeather = lv_obj_create(ui_PanelMove);
    lv_obj_remove_style_all(ui_ContainerWeather);
    lv_obj_set_width(ui_ContainerWeather, lv_pct(80));
    lv_obj_set_height(ui_ContainerWeather, lv_pct(80));
    lv_obj_set_align(ui_ContainerWeather, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_ContainerWeather, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image17 = lv_img_create(ui_ContainerWeather);
    lv_img_set_src(ui_Image17, &ui_img_indicator_bg_weather_png);
    lv_obj_set_width(ui_Image17, LV_SIZE_CONTENT);   /// 153
    lv_obj_set_height(ui_Image17, LV_SIZE_CONTENT);    /// 153
    lv_obj_set_align(ui_Image17, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image17, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image17, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image19 = lv_img_create(ui_ContainerWeather);
    lv_img_set_src(ui_Image19, &ui_img_1784134941);
    lv_obj_set_width(ui_Image19, LV_SIZE_CONTENT);   /// 260
    lv_obj_set_height(ui_Image19, LV_SIZE_CONTENT);    /// 251
    lv_obj_set_align(ui_Image19, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image19, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image19, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ContainerVariables = lv_obj_create(ui_Panel_Principal);
    lv_obj_remove_style_all(ui_ContainerVariables);
    lv_obj_set_height(ui_ContainerVariables, 148);
    lv_obj_set_width(ui_ContainerVariables, lv_pct(40));
    lv_obj_set_x(ui_ContainerVariables, 0);
    lv_obj_set_y(ui_ContainerVariables, 40);
    lv_obj_set_align(ui_ContainerVariables, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_ContainerVariables, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_ContainerVariables, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_ContainerVariables, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelVariables = lv_obj_create(ui_ContainerVariables);
    lv_obj_set_width(ui_PanelVariables, 170);
    lv_obj_set_height(ui_PanelVariables, 45);
    lv_obj_set_x(ui_PanelVariables, -10);
    lv_obj_set_y(ui_PanelVariables, 0);
    lv_obj_set_align(ui_PanelVariables, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_PanelVariables, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelVariables, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelVariables, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelVariables, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelVariables, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelVariables, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelVariables, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelVariables, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelVariables, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelVariables, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelVariables, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelVariables, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelVariables, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelVariables, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelRad = lv_obj_create(ui_PanelVariables);
    lv_obj_set_width(ui_PanelRad, lv_pct(50));
    lv_obj_set_height(ui_PanelRad, lv_pct(100));
    lv_obj_set_align(ui_PanelRad, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_PanelRad, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelRad, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelRad, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelRad, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelRad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelRad, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelRad, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRad, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRad, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRad, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVarRad = lv_label_create(ui_PanelRad);
    lv_obj_set_width(ui_LabelVarRad, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVarRad, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelVarRad, 5);
    lv_obj_set_x(ui_LabelVarRad, lv_pct(0));
    lv_obj_set_align(ui_LabelVarRad, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelVarRad, "850");
    lv_obj_set_style_text_color(ui_LabelVarRad, lv_color_hex(0xF3ECEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVarRad, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelVarRad, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVarRad, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitle = lv_label_create(ui_PanelRad);
    lv_obj_set_width(ui_LabelTitle, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitle, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitle, 0);
    lv_obj_set_y(ui_LabelTitle, -10);
    lv_obj_set_align(ui_LabelTitle, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitle, "Radiation");
    ui_object_set_themeable_style_property(ui_LabelTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_COLOR,
                                           _ui_theme_color_LETTER_MID);
    ui_object_set_themeable_style_property(ui_LabelTitle, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_TEXT_OPA,
                                           _ui_theme_alpha_LETTER_MID);
    lv_obj_set_style_text_font(ui_LabelTitle, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUnits = lv_label_create(ui_PanelRad);
    lv_obj_set_width(ui_LabelUnits, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUnits, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUnits, 2);
    lv_obj_set_y(ui_LabelUnits, 7);
    lv_obj_set_align(ui_LabelUnits, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_LabelUnits, "W/m2");
    lv_obj_set_style_text_color(ui_LabelUnits, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUnits, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUnits, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_LabelUnits, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon = lv_img_create(ui_PanelRad);
    lv_img_set_src(ui_icon, &ui_img_icon_radiacion_png);
    lv_obj_set_width(ui_icon, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_icon, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_icon, 0);
    lv_obj_set_y(ui_icon, 3);
    lv_obj_set_align(ui_icon, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_icon, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Line = lv_obj_create(ui_PanelVariables);
    lv_obj_set_width(ui_Line, 2);
    lv_obj_set_height(ui_Line, 50);
    lv_obj_set_align(ui_Line, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Line, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Line, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Line, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Line, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Line, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Line, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTemp = lv_obj_create(ui_PanelVariables);
    lv_obj_set_width(ui_PanelTemp, lv_pct(50));
    lv_obj_set_height(ui_PanelTemp, lv_pct(100));
    lv_obj_set_align(ui_PanelTemp, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_PanelTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTemp, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTemp, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTemp, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTemp, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVarTemp = lv_label_create(ui_PanelTemp);
    lv_obj_set_width(ui_LabelVarTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVarTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelVarTemp, 5);
    lv_obj_set_x(ui_LabelVarTemp, lv_pct(0));
    lv_obj_set_align(ui_LabelVarTemp, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelVarTemp, "450");
    lv_obj_set_style_text_color(ui_LabelVarTemp, lv_color_hex(0xF3ECEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVarTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelVarTemp, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVarTemp, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitle1 = lv_label_create(ui_PanelTemp);
    lv_obj_set_width(ui_LabelTitle1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitle1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitle1, 0);
    lv_obj_set_y(ui_LabelTitle1, -10);
    lv_obj_set_align(ui_LabelTitle1, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitle1, "Temperature");
    lv_obj_set_style_text_color(ui_LabelTitle1, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitle1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTitle1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUnits1 = lv_label_create(ui_PanelTemp);
    lv_obj_set_width(ui_LabelUnits1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUnits1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUnits1, 2);
    lv_obj_set_y(ui_LabelUnits1, 7);
    lv_obj_set_align(ui_LabelUnits1, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_LabelUnits1, "°C");
    lv_obj_set_style_text_color(ui_LabelUnits1, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUnits1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUnits1, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_LabelUnits1, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon1 = lv_img_create(ui_PanelTemp);
    lv_img_set_src(ui_icon1, &ui_img_icon_temperatura_png);
    lv_obj_set_width(ui_icon1, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_icon1, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_icon1, 0);
    lv_obj_set_y(ui_icon1, 3);
    lv_obj_set_align(ui_icon1, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_icon1, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelVariables1 = lv_obj_create(ui_ContainerVariables);
    lv_obj_set_width(ui_PanelVariables1, 170);
    lv_obj_set_height(ui_PanelVariables1, 45);
    lv_obj_set_x(ui_PanelVariables1, -10);
    lv_obj_set_y(ui_PanelVariables1, lv_pct(33));
    lv_obj_set_align(ui_PanelVariables1, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_PanelVariables1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelVariables1, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelVariables1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelVariables1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelVariables1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelVariables1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelVariables1, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelVariables1, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelVariables1, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelVariables1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelVariables1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelVariables1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelVariables1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelVariables1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelHum = lv_obj_create(ui_PanelVariables1);
    lv_obj_set_width(ui_PanelHum, lv_pct(50));
    lv_obj_set_height(ui_PanelHum, lv_pct(100));
    lv_obj_set_align(ui_PanelHum, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_PanelHum, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelHum, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelHum, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelHum, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelHum, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelHum, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelHum, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVarHum = lv_label_create(ui_PanelHum);
    lv_obj_set_width(ui_LabelVarHum, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVarHum, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelVarHum, 5);
    lv_obj_set_x(ui_LabelVarHum, lv_pct(0));
    lv_obj_set_align(ui_LabelVarHum, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelVarHum, "45");
    lv_obj_set_style_text_color(ui_LabelVarHum, lv_color_hex(0xF3ECEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVarHum, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelVarHum, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVarHum, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitle2 = lv_label_create(ui_PanelHum);
    lv_obj_set_width(ui_LabelTitle2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitle2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitle2, 0);
    lv_obj_set_y(ui_LabelTitle2, -10);
    lv_obj_set_align(ui_LabelTitle2, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitle2, "Humidity");
    lv_obj_set_style_text_color(ui_LabelTitle2, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitle2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTitle2, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUnits2 = lv_label_create(ui_PanelHum);
    lv_obj_set_width(ui_LabelUnits2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUnits2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUnits2, 2);
    lv_obj_set_y(ui_LabelUnits2, 7);
    lv_obj_set_align(ui_LabelUnits2, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_LabelUnits2, "%");
    lv_obj_set_style_text_color(ui_LabelUnits2, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUnits2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUnits2, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_LabelUnits2, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon2 = lv_img_create(ui_PanelHum);
    lv_img_set_src(ui_icon2, &ui_img_icon_humedad_png);
    lv_obj_set_width(ui_icon2, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_icon2, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_icon2, 0);
    lv_obj_set_y(ui_icon2, 3);
    lv_obj_set_align(ui_icon2, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_icon2, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Line1 = lv_obj_create(ui_PanelVariables1);
    lv_obj_set_width(ui_Line1, 2);
    lv_obj_set_height(ui_Line1, 50);
    lv_obj_set_align(ui_Line1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Line1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Line1, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Line1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Line1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Line1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Line1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTempExt = lv_obj_create(ui_PanelVariables1);
    lv_obj_set_width(ui_PanelTempExt, lv_pct(50));
    lv_obj_set_height(ui_PanelTempExt, lv_pct(100));
    lv_obj_set_align(ui_PanelTempExt, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_PanelTempExt, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTempExt, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTempExt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelTempExt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelTempExt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTempExt, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTempExt, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTempExt, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTempExt, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTempExt, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVarTempExt = lv_label_create(ui_PanelTempExt);
    lv_obj_set_width(ui_LabelVarTempExt, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVarTempExt, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelVarTempExt, 5);
    lv_obj_set_x(ui_LabelVarTempExt, lv_pct(0));
    lv_obj_set_align(ui_LabelVarTempExt, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelVarTempExt, "30");
    lv_obj_set_style_text_color(ui_LabelVarTempExt, lv_color_hex(0xF3ECEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVarTempExt, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelVarTempExt, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVarTempExt, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitle3 = lv_label_create(ui_PanelTempExt);
    lv_obj_set_width(ui_LabelTitle3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitle3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitle3, 0);
    lv_obj_set_y(ui_LabelTitle3, -10);
    lv_obj_set_align(ui_LabelTitle3, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitle3, "Ext. Temp.");
    lv_obj_set_style_text_color(ui_LabelTitle3, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitle3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTitle3, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUnits3 = lv_label_create(ui_PanelTempExt);
    lv_obj_set_width(ui_LabelUnits3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUnits3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUnits3, 2);
    lv_obj_set_y(ui_LabelUnits3, 7);
    lv_obj_set_align(ui_LabelUnits3, LV_ALIGN_BOTTOM_RIGHT);
    lv_label_set_text(ui_LabelUnits3, "°C");
    lv_obj_set_style_text_color(ui_LabelUnits3, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUnits3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUnits3, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_LabelUnits3, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon3 = lv_img_create(ui_PanelTempExt);
    lv_img_set_src(ui_icon3, &ui_img_icon_temperatura_png);
    lv_obj_set_width(ui_icon3, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_icon3, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_icon3, 0);
    lv_obj_set_y(ui_icon3, 3);
    lv_obj_set_align(ui_icon3, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_icon3, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelVariables2 = lv_obj_create(ui_ContainerVariables);
    lv_obj_set_width(ui_PanelVariables2, 170);
    lv_obj_set_height(ui_PanelVariables2, 45);
    lv_obj_set_x(ui_PanelVariables2, -10);
    lv_obj_set_y(ui_PanelVariables2, lv_pct(66));
    lv_obj_set_align(ui_PanelVariables2, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_PanelVariables2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelVariables2, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelVariables2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelVariables2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelVariables2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelVariables2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelVariables2, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelVariables2, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelVariables2, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelVariables2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelVariables2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelVariables2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelVariables2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelVariables2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelAzimut = lv_obj_create(ui_PanelVariables2);
    lv_obj_set_width(ui_PanelAzimut, lv_pct(50));
    lv_obj_set_height(ui_PanelAzimut, lv_pct(100));
    lv_obj_set_align(ui_PanelAzimut, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_PanelAzimut, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelAzimut, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelAzimut, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelAzimut, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelAzimut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelAzimut, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelAzimut, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelAzimut, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelAzimut, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelAzimut, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVarAzimut = lv_label_create(ui_PanelAzimut);
    lv_obj_set_width(ui_LabelVarAzimut, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVarAzimut, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelVarAzimut, 5);
    lv_obj_set_x(ui_LabelVarAzimut, lv_pct(0));
    lv_obj_set_align(ui_LabelVarAzimut, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelVarAzimut, "50");
    lv_obj_set_style_text_color(ui_LabelVarAzimut, lv_color_hex(0xF3ECEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVarAzimut, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelVarAzimut, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVarAzimut, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitle4 = lv_label_create(ui_PanelAzimut);
    lv_obj_set_width(ui_LabelTitle4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitle4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitle4, 0);
    lv_obj_set_y(ui_LabelTitle4, -10);
    lv_obj_set_align(ui_LabelTitle4, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitle4, "Azimut");
    lv_obj_set_style_text_color(ui_LabelTitle4, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitle4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTitle4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUnits4 = lv_label_create(ui_PanelAzimut);
    lv_obj_set_width(ui_LabelUnits4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUnits4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUnits4, 2);
    lv_obj_set_y(ui_LabelUnits4, 7);
    lv_obj_set_align(ui_LabelUnits4, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelUnits4, "°");
    lv_obj_set_style_text_color(ui_LabelUnits4, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUnits4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUnits4, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_LabelUnits4, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon4 = lv_img_create(ui_PanelAzimut);
    lv_img_set_src(ui_icon4, &ui_img_icon_objetivo_png);
    lv_obj_set_width(ui_icon4, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_icon4, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_icon4, 0);
    lv_obj_set_y(ui_icon4, 3);
    lv_obj_set_align(ui_icon4, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_icon4, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Line2 = lv_obj_create(ui_PanelVariables2);
    lv_obj_set_width(ui_Line2, 2);
    lv_obj_set_height(ui_Line2, 50);
    lv_obj_set_align(ui_Line2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Line2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Line2, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Line2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Line2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Line2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Line2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelCenit = lv_obj_create(ui_PanelVariables2);
    lv_obj_set_width(ui_PanelCenit, lv_pct(50));
    lv_obj_set_height(ui_PanelCenit, lv_pct(100));
    lv_obj_set_align(ui_PanelCenit, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_PanelCenit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelCenit, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelCenit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelCenit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelCenit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelCenit, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelCenit, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelCenit, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelCenit, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelCenit, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelVarCenit = lv_label_create(ui_PanelCenit);
    lv_obj_set_width(ui_LabelVarCenit, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelVarCenit, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_y(ui_LabelVarCenit, 5);
    lv_obj_set_x(ui_LabelVarCenit, lv_pct(0));
    lv_obj_set_align(ui_LabelVarCenit, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LabelVarCenit, "30");
    lv_obj_set_style_text_color(ui_LabelVarCenit, lv_color_hex(0xF3ECEC), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelVarCenit, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelVarCenit, LV_TEXT_ALIGN_RIGHT, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelVarCenit, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelTitle5 = lv_label_create(ui_PanelCenit);
    lv_obj_set_width(ui_LabelTitle5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitle5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitle5, 0);
    lv_obj_set_y(ui_LabelTitle5, -10);
    lv_obj_set_align(ui_LabelTitle5, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitle5, "Cenit");
    lv_obj_set_style_text_color(ui_LabelTitle5, lv_color_hex(0x9098AA), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitle5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTitle5, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelUnits5 = lv_label_create(ui_PanelCenit);
    lv_obj_set_width(ui_LabelUnits5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelUnits5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelUnits5, 2);
    lv_obj_set_y(ui_LabelUnits5, 7);
    lv_obj_set_align(ui_LabelUnits5, LV_ALIGN_TOP_RIGHT);
    lv_label_set_text(ui_LabelUnits5, "°");
    lv_obj_set_style_text_color(ui_LabelUnits5, lv_color_hex(0x808080), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelUnits5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelUnits5, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_transform_zoom(ui_LabelUnits5, 256, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon5 = lv_img_create(ui_PanelCenit);
    lv_img_set_src(ui_icon5, &ui_img_icon_objetivo_png);
    lv_obj_set_width(ui_icon5, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_icon5, LV_SIZE_CONTENT);    /// 50
    lv_obj_set_x(ui_icon5, 0);
    lv_obj_set_y(ui_icon5, 3);
    lv_obj_set_align(ui_icon5, LV_ALIGN_BOTTOM_LEFT);
    lv_obj_add_flag(ui_icon5, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelMode = lv_obj_create(ui_Panel_Principal);
    lv_obj_set_width(ui_PanelMode, lv_pct(40));
    lv_obj_set_height(ui_PanelMode, lv_pct(39));
    lv_obj_set_x(ui_PanelMode, 0);
    lv_obj_set_y(ui_PanelMode, -2);
    lv_obj_set_align(ui_PanelMode, LV_ALIGN_TOP_RIGHT);
    lv_obj_clear_flag(ui_PanelMode, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelMode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelMode, 5, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelMode, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Container3 = lv_obj_create(ui_PanelMode);
    lv_obj_remove_style_all(ui_Container3);
    lv_obj_set_width(ui_Container3, lv_pct(50));
    lv_obj_set_height(ui_Container3, lv_pct(46));
    lv_obj_set_align(ui_Container3, LV_ALIGN_LEFT_MID);
    lv_obj_set_flex_flow(ui_Container3, LV_FLEX_FLOW_ROW_WRAP);
    lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_SPACE_BETWEEN);
    lv_obj_clear_flag(ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LabelTitle7 = lv_label_create(ui_Container3);
    lv_obj_set_width(ui_LabelTitle7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelTitle7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelTitle7, 0);
    lv_obj_set_y(ui_LabelTitle7, 10);
    lv_obj_set_align(ui_LabelTitle7, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_LabelTitle7, "MANUAL / AUTO");
    lv_obj_set_style_text_color(ui_LabelTitle7, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelTitle7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelTitle7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelTitle7, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch1 = lv_switch_create(ui_Container3);
    lv_obj_set_width(ui_Switch1, 72);
    lv_obj_set_height(ui_Switch1, 32);
    lv_obj_set_x(ui_Switch1, 2);
    lv_obj_set_y(ui_Switch1, 6);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x191D26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch1, lv_color_hex(0x7C92BA), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch1, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Container1 = lv_obj_create(ui_PanelMode);
    lv_obj_remove_style_all(ui_Container1);
    lv_obj_set_width(ui_Container1, lv_pct(50));
    lv_obj_set_height(ui_Container1, lv_pct(100));
    lv_obj_set_align(ui_Container1, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Image20 = lv_img_create(ui_Container1);
    lv_img_set_src(ui_Image20, &ui_img_indicator_bg_mode2_png);
    lv_obj_set_width(ui_Image20, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Image20, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Image20, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image20, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image20, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_img_set_zoom(ui_Image20, 255);

    ui_RollerModes = lv_roller_create(ui_Container1);
    lv_roller_set_options(ui_RollerModes, "Sleep\nManual\nAuto\nSunny", LV_ROLLER_MODE_INFINITE);
    lv_obj_set_width(ui_RollerModes, lv_pct(85));
    lv_obj_set_height(ui_RollerModes, lv_pct(85));
    lv_obj_set_align(ui_RollerModes, LV_ALIGN_CENTER);
    lv_obj_set_style_text_color(ui_RollerModes, lv_color_hex(0x3F475E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerModes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RollerModes, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_decor(ui_RollerModes, LV_TEXT_DECOR_NONE, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerModes, &lv_font_montserrat_8, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerModes, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerModes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_RollerModes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_RollerModes, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RollerModes, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_color(ui_RollerModes, lv_color_hex(0xDBE6FF), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_RollerModes, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_RollerModes, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_RollerModes, &lv_font_montserrat_12, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RollerModes, lv_color_hex(0x3A445C), LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RollerModes, 255, LV_PART_SELECTED | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RollerModes, 0, LV_PART_SELECTED | LV_STATE_DEFAULT);

    ui_PanelNotification = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelNotification, lv_pct(90));
    lv_obj_set_height(ui_PanelNotification, lv_pct(8));
    lv_obj_set_align(ui_PanelNotification, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_PanelNotification, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNotification, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNotification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelNotification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelNotification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelNotification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelNotification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelNotification, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelNotification = lv_label_create(ui_PanelNotification);
    lv_obj_set_width(ui_LabelNotification, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelNotification, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LabelNotification, 5);
    lv_obj_set_y(ui_LabelNotification, 0);
    lv_obj_set_align(ui_LabelNotification, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LabelNotification, "Aqui va toda la informacion...");
    lv_obj_set_style_text_color(ui_LabelNotification, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelNotification, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelNotification, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelNotification, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelNotificationIcon = lv_obj_create(ui_PanelNotification);
    lv_obj_set_width(ui_PanelNotificationIcon, lv_pct(30));
    lv_obj_set_height(ui_PanelNotificationIcon, lv_pct(100));
    lv_obj_set_align(ui_PanelNotificationIcon, LV_ALIGN_RIGHT_MID);
    lv_obj_set_flex_flow(ui_PanelNotificationIcon, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_PanelNotificationIcon, LV_FLEX_ALIGN_END, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_obj_clear_flag(ui_PanelNotificationIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelNotificationIcon, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelNotificationIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelNotificationIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelNotificationIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelNotificationIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelNotificationIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelNotificationIcon, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_icon8 = lv_img_create(ui_PanelNotificationIcon);
    lv_img_set_src(ui_icon8, &ui_img_99760210);
    lv_obj_set_width(ui_icon8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_icon8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_icon8, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_icon8, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_icon7 = lv_img_create(ui_PanelNotificationIcon);
    lv_img_set_src(ui_icon7, &ui_img_821389505);
    lv_obj_set_width(ui_icon7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_icon7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_icon7, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_icon7, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_icon9 = lv_img_create(ui_PanelNotificationIcon);
    lv_img_set_src(ui_icon9, &ui_img_1640394774);
    lv_obj_set_width(ui_icon9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_icon9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_icon9, LV_ALIGN_RIGHT_MID);
    lv_obj_add_flag(ui_icon9, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_icon9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_PanelTimeAndDate = lv_obj_create(ui_Screen1);
    lv_obj_set_width(ui_PanelTimeAndDate, lv_pct(40));
    lv_obj_set_height(ui_PanelTimeAndDate, lv_pct(8));
    lv_obj_set_x(ui_PanelTimeAndDate, -15);
    lv_obj_set_y(ui_PanelTimeAndDate, 5);
    lv_obj_set_align(ui_PanelTimeAndDate, LV_ALIGN_BOTTOM_RIGHT);
    lv_obj_clear_flag(ui_PanelTimeAndDate, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTimeAndDate, lv_color_hex(0x090909), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTimeAndDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelTimeAndDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelTimeAndDate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTimeAndDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_PanelTimeAndDate, lv_color_hex(0x414B62), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_PanelTimeAndDate, 100, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_PanelTimeAndDate, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_PanelTimeAndDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTimeAndDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTimeAndDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTimeAndDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTimeAndDate, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelRad3 = lv_obj_create(ui_PanelTimeAndDate);
    lv_obj_set_width(ui_PanelRad3, lv_pct(50));
    lv_obj_set_height(ui_PanelRad3, lv_pct(100));
    lv_obj_set_align(ui_PanelRad3, LV_ALIGN_LEFT_MID);
    lv_obj_clear_flag(ui_PanelRad3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelRad3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelRad3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelRad3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelRad3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelRad3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelRad3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelRad3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelRad3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelRad3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDate4 = lv_label_create(ui_PanelRad3);
    lv_obj_set_width(ui_LabelDate4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelDate4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDate4, "01:52 PM");
    lv_obj_set_style_text_color(ui_LabelDate4, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDate4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelDate4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDate4, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Line5 = lv_obj_create(ui_PanelTimeAndDate);
    lv_obj_set_width(ui_Line5, 2);
    lv_obj_set_height(ui_Line5, 50);
    lv_obj_set_align(ui_Line5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Line5, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Line5, lv_color_hex(0x3A3F4B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Line5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_Line5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_Line5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Line5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_PanelTemp3 = lv_obj_create(ui_PanelTimeAndDate);
    lv_obj_set_width(ui_PanelTemp3, lv_pct(50));
    lv_obj_set_height(ui_PanelTemp3, lv_pct(100));
    lv_obj_set_align(ui_PanelTemp3, LV_ALIGN_RIGHT_MID);
    lv_obj_clear_flag(ui_PanelTemp3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_PanelTemp3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_PanelTemp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_main_stop(ui_PanelTemp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_stop(ui_PanelTemp3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_PanelTemp3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_PanelTemp3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_PanelTemp3, 6, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_PanelTemp3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_PanelTemp3, 12, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LabelDate1 = lv_label_create(ui_PanelTemp3);
    lv_obj_set_width(ui_LabelDate1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LabelDate1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_LabelDate1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LabelDate1, "28/10/2024");
    lv_obj_set_style_text_color(ui_LabelDate1, lv_color_hex(0xD2DCF2), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LabelDate1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LabelDate1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_LabelDate1, &lv_font_montserrat_10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Glow_R, ui_event_Glow_R, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Glow_L, ui_event_Glow_L, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Glow_U, ui_event_Glow_U, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Glow_D, ui_event_Glow_D, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    uic_PanelMove = ui_PanelMove;
    uic_btnRigth = ui_btnRigth;

}
