// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Controlador Seguidor Solar

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_FRONT[2] = {0x7C92BA, 0x7C92BA};
const ui_theme_variable_t _ui_theme_alpha_FRONT[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_BACK[2] = {0x191D26, 0x191D26};
const ui_theme_variable_t _ui_theme_alpha_BACK[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_LETTER[2] = {0xD2DCF2, 0xD2DCF2};
const ui_theme_variable_t _ui_theme_alpha_LETTER[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_SELECT[2] = {0x3A445C, 0x3A445C};
const ui_theme_variable_t _ui_theme_alpha_SELECT[2] = {255, 255};

const ui_theme_variable_t _ui_theme_color_LETTER_MID[2] = {0x9098AA, 0x9098AA};
const ui_theme_variable_t _ui_theme_alpha_LETTER_MID[2] = {255, 255};
uint8_t ui_theme_idx = UI_THEME_GRISES;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

