// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Controlador Seguidor Solar

#ifndef _UI_THEMES_H
#define _UI_THEMES_H

#ifdef __cplusplus
extern "C" {
#endif

#define UI_THEME_COLOR_FRONT 0
#define UI_THEME_COLOR_BACK 1
#define UI_THEME_COLOR_LETTER 2
#define UI_THEME_COLOR_SELECT 3
#define UI_THEME_COLOR_LETTER_MID 4

#define UI_THEME_DEFAULT 0

#define UI_THEME_GRISES 1

extern const ui_theme_variable_t _ui_theme_color_FRONT[2];
extern const ui_theme_variable_t _ui_theme_alpha_FRONT[2];

extern const ui_theme_variable_t _ui_theme_color_BACK[2];
extern const ui_theme_variable_t _ui_theme_alpha_BACK[2];

extern const ui_theme_variable_t _ui_theme_color_LETTER[2];
extern const ui_theme_variable_t _ui_theme_alpha_LETTER[2];

extern const ui_theme_variable_t _ui_theme_color_SELECT[2];
extern const ui_theme_variable_t _ui_theme_alpha_SELECT[2];

extern const ui_theme_variable_t _ui_theme_color_LETTER_MID[2];
extern const ui_theme_variable_t _ui_theme_alpha_LETTER_MID[2];

extern const uint32_t * ui_theme_colors[2];
extern const uint8_t * ui_theme_alphas[2];
extern uint8_t ui_theme_idx;

void ui_theme_set(uint8_t theme_idx);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
